---
arch_hostname: mediaserver
arch_timezone: Europe/Warsaw

arch_host_pacman_packages_extra:
  - 7zip
  - calibre
  - tailscale
  - uv
arch_host_aur_packages_extra:
  - bazarr
  - flaresolverr
  - hermes-agent
  - kcc
  - prowlarr
  - radarr
  - sonarr
arch_host_system_services_extra:
  - bazarr
  - flaresolverr
  - prowlarr
  - radarr
  - sonarr
  - tailscaled
arch_host_firewall_allowed_tcp_ports_extra:
  - 7878
  - 8989
  - 9696
arch_host_firewall_allowed_udp_ports_extra:
  - 41641
arch_host_firewall_trusted_interfaces_extra:
  - tailscale0

arch_extra_mounts:
  - enabled: true
    src: "LABEL=MEDIA"
    path: /mnt/media
    fstype: ext4
    opts: defaults,nofail,x-systemd.device-timeout=10
    mode: "2775"

arch_transmission_download_dir: /mnt/media/downloads
arch_transmission_download_categories:
  - radarr
  - tv-sonarr

arch_hermes_agent_enabled: true
arch_hermes_agent_provider: xai
arch_hermes_agent_base_url: https://api.x.ai/v1
arch_hermes_agent_model: grok-4.3
arch_hermes_agent_gateway_service_enabled: true

arch_flaresolverr_enabled: true
