---
arch_hostname: rejewski
arch_timezone: Europe/Berlin
arch_console_keymap: de-latin1-nodeadkeys
arch_manage_grub_kernel_parameters: true

arch_hosts_entries:
  - "127.0.0.1 localhost.localdomain localhost"
  - "136.243.134.187 rejewski.vitorpy.com rejewski"
  - "::1 ip6-localhost ip6-loopback"
  - "fe00::0 ip6-localnet"
  - "ff00::0 ip6-mcastprefix"
  - "ff02::1 ip6-allnodes"
  - "ff02::2 ip6-allrouters"
  - "ff02::3 ip6-allhosts"
  - "2a01:4f8:212:3662::2 rejewski.vitorpy.com rejewski"

arch_host_system_services_extra:
  - nginx

arch_host_firewall_allowed_tcp_ports_extra:
  - 80
  - 443

arch_host_pacman_packages_extra:
  - nginx
  - certbot

arch_web_proxy_enabled: true
arch_web_proxy_server_name: rejewski.vitorpy.com
arch_web_proxy_upstream_host: 127.0.0.1
arch_web_proxy_upstream_port: 18789
arch_web_proxy_acme_email: vitor@vitorpy.com
arch_web_proxy_control_ui_allowed_origins:
  - https://rejewski.vitorpy.com
arch_openclaw_cli_path: /home/vitorpy/.nvm/versions/node/v24.10.0/bin/openclaw
