---
- name: Ensure X11 keyboard config directory exists
  ansible.builtin.file:
    path: /etc/X11/xorg.conf.d
    state: directory
    mode: "0755"

- name: Manage X11 keyboard layout
  ansible.builtin.template:
    src: 00-keyboard.conf.j2
    dest: /etc/X11/xorg.conf.d/00-keyboard.conf
    mode: "0644"
