preload = /home/vitorpy/.local/share/google-arts/current.webp
ipc = true
splash = false

wallpaper {
    monitor = eDP-1
    path = /home/vitorpy/.local/share/google-arts/current.webp
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = /home/vitorpy/.local/share/google-arts/current.webp
    fit_mode = cover
}
