ipc = true
splash = false

wallpaper {
    monitor =
    path = /home/vitorpy/.local/share/arts-wallpaper/current.webp
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = /home/vitorpy/.local/share/arts-wallpaper/current.webp
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = /home/vitorpy/.local/share/arts-wallpaper/current.webp
    fit_mode = cover
}
