ipc = true
splash = false

wallpaper {
    monitor =
    path = /var/lib/arts-wallpaper/current.webp
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = /var/lib/arts-wallpaper/current.webp
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = /var/lib/arts-wallpaper/current.webp
    fit_mode = cover
}
