// Generated by sf-symbols-map render-qml; do not edit.
// Artifact profile: sf-symbols-8-build-135

import QtQuick

QtObject {
    readonly property string speakerMuted: "􀊣" // speaker.slash.fill (U+1002A3)
    readonly property string speakerLow: "􀊥" // speaker.wave.1.fill (U+1002A5)
    readonly property string speakerHigh: "􀊧" // speaker.wave.2.fill (U+1002A7)
    readonly property string headphones: "􀑈" // headphones (U+100448)
    readonly property string microphone: "􀊱" // microphone.fill (U+1002B1)
    readonly property string microphoneMuted: "􀊳" // microphone.slash.fill (U+1002B3)
    readonly property string brightness: "􀆮" // sun.max.fill (U+1001AE)
    readonly property var batteryLevels: [
        "􀛪", // battery.0percent (U+1006EA)
        "􀛩", // battery.25percent (U+1006E9)
        "􀺶", // battery.50percent (U+100EB6)
        "􀺸", // battery.75percent (U+100EB8)
        "􀛨" // battery.100percent (U+1006E8)
    ]
    readonly property string batteryCharging: "􀢋" // battery.100percent.bolt (U+10088B)
    readonly property string cpu: "􀧓" // cpu.fill (U+1009D3)
    readonly property string temperature: "􀇬" // thermometer.medium (U+1001EC)
    readonly property string power: "􀆨" // power (U+1001A8)
    readonly property string dndEnabled: "􀋞" // bell.slash.fill (U+1002DE)
    readonly property string dndDisabled: "􀋚" // bell.fill (U+1002DA)
    readonly property string mail: "􀛮" // envelope.fill (U+1006EE)
    readonly property string updates: "􀁹" // arrow.down.circle.fill (U+100079)
    readonly property string reboot: "􀚂" // arrow.clockwise.circle.fill (U+100682)
    readonly property string warning: "􀇿" // exclamationmark.triangle.fill (U+1001FF)
}
