---
- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: Reload nftables
  ansible.builtin.systemd:
    name: nftables
    state: restarted

- name: Apply sysctl hardening
  ansible.builtin.command: sysctl --system
  changed_when: true
