---
arch_desktop_enabled: true
arch_ly_enabled: true

arch_pacman_packages: "{{ arch_pacman_packages_base + arch_pacman_packages_browsers + arch_pacman_packages_hyprland + arch_pacman_packages_gnome + arch_pacman_packages_multimedia + arch_pacman_packages_sway + arch_pacman_packages_development + arch_pacman_packages_communication + arch_pacman_packages_theming + arch_pacman_packages_utilities }}"

arch_aur_packages: "{{ arch_aur_packages_hyprland + arch_aur_packages_sway + arch_aur_packages_development + arch_aur_packages_communication + arch_aur_packages_theming + arch_aur_packages_utilities }}"
