---
- name: Check for managed ly config.ini
  ansible.builtin.stat:
    path: "{{ arch_primary_user_home }}/.config/ly/config.ini"
  register: ly_config

- name: Check for managed ly setup.sh
  ansible.builtin.stat:
    path: "{{ arch_primary_user_home }}/.config/ly/setup.sh"
  register: ly_setup

- name: Install ly config.ini
  ansible.builtin.copy:
    src: "{{ arch_primary_user_home }}/.config/ly/config.ini"
    dest: /etc/ly/config.ini
    remote_src: true
    mode: "0644"
  when: ly_config.stat.exists

- name: Install ly setup.sh
  ansible.builtin.copy:
    src: "{{ arch_primary_user_home }}/.config/ly/setup.sh"
    dest: /etc/ly/setup.sh
    remote_src: true
    mode: "0755"
  when: ly_setup.stat.exists

- name: Enable ly display manager
  ansible.builtin.systemd:
    name: "{{ arch_ly_service_name }}"
    enabled: true
    state: started
