---
all:
  children:
    workstation:
      hosts:
        localhost:
          ansible_connection: local
    server:
      hosts:
        dembe:
          ansible_host: 148.251.54.9
          ansible_user: vitorpy
      children:
        devbox:
          hosts:
            rejewski:
              ansible_host: rejewski.vitorpy.com
              ansible_user: vitorpy
            scherbius:
              ansible_host: scherbius.vitorpy.com
              ansible_user: vitorpy
        web:
          hosts:
            scherbius: {}
        media_servers:
          hosts:
            mediaserver:
              ansible_host: mediaserver.vitorpy.com
              ansible_user: vitorpy
