---
all:
  children:
    workstation:
      hosts:
        localhost:
          ansible_connection: local
    server:
      children:
        devbox:
          hosts:
            rejewski:
              ansible_host: rejewski.vitorpy.com
              ansible_user: vitorpy
            scherbius:
              ansible_host: scherbius.vitorpy.com
              ansible_user: vitorpy
        web:
          hosts:
            scherbius: {}
        media_servers:
          hosts:
            mediaserver:
              ansible_host: mediaserver.vitorpy.com
              ansible_user: vitorpy
