---
all:
  children:
    workstation:
      hosts:
        localhost:
          ansible_connection: local
    server:
      hosts:
        rejewski:
          ansible_host: rejewski.vitorpy.com
          ansible_user: vitorpy
