#!/usr/bin/env python3
"""Read-only PCR key/UKI checks. Only expected metadata absence requests a rebuild."""

import argparse
import base64
import hashlib
import json
from pathlib import Path
import subprocess

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding, rsa


def public_der(pem):
    return serialization.load_pem_public_key(pem).public_bytes(
        serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo
    )


def key_fingerprint(pem):
    # systemd fingerprints RSA keys in PKCS#1 DER, not SubjectPublicKeyInfo DER.
    key = serialization.load_pem_public_key(pem)
    if not isinstance(key, rsa.RSAPublicKey):
        raise ValueError("Expected an RSA key generated by ukify genkey")
    return hashlib.sha256(key.public_bytes(
        serialization.Encoding.DER, serialization.PublicFormat.PKCS1
    )).hexdigest()


def check_pair(private_path, public_path):
    private = Path(private_path)
    public = Path(public_path)
    if private.is_symlink() or public.is_symlink():
        raise ValueError("PCR key paths must not be symlinks")
    if not private.exists() and not public.exists():
        return {"exists": False}
    if not private.is_file() or not public.is_file():
        raise ValueError("Incomplete PCR key pair; refusing to replace either key")
    key = serialization.load_pem_private_key(private.read_bytes(), password=None)
    actual = key.public_key().public_bytes(
        serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo
    )
    if actual != public_der(public.read_bytes()):
        raise ValueError("PCR private and public keys do not match")
    return {"exists": True, "fingerprint": key_fingerprint(public.read_bytes())}


def check_sections(sections, public_pem):
    if not all(name in sections for name in (".pcrpkey", ".pcrsig")):
        return {"valid": False, "reason": "Missing PCR key or signature section"}
    expected = public_der(public_pem)
    embedded = public_der(sections[".pcrpkey"]["text"].encode())
    if embedded != expected:
        return {"valid": False, "reason": "Embedded PCR key differs from managed key"}
    signatures = json.loads(sections[".pcrsig"]["text"])
    fingerprint = key_fingerprint(public_pem)
    for signature in signatures.get("sha256", []):
        if (signature.get("pcrs") == [11]
                and signature.get("ref") == "initrd"
                and signature.get("pkfp") == fingerprint):
            if len(bytes.fromhex(signature["pol"])) != 32:
                raise ValueError("Invalid initrd policy digest length")
            signed = base64.b64decode(signature["sig"], validate=True)
            if not signed:
                raise ValueError("Empty PCR policy signature")
            serialization.load_pem_public_key(public_pem).verify(
                signed, bytes.fromhex(signature["pol"]) + hashlib.sha256(b"initrd").digest(),
                padding.PKCS1v15(), hashes.SHA256(),
            )
            return {"valid": True, "fingerprint": fingerprint}
    return {"valid": False, "reason": "Missing matching SHA-256 PCR 11 initrd policy"}


def check_uki(image_path, public_path):
    if not Path(image_path).exists() or not Path(public_path).exists():
        return {"valid": False, "reason": "UKI or public key not yet present"}
    output = subprocess.check_output([
        "ukify", "--json=short", "--section=.pcrpkey:text",
        "--section=.pcrsig:text", "inspect", image_path,
    ], text=True)
    return check_sections(json.loads(output), Path(public_path).read_bytes())


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=("pair", "uki"))
    parser.add_argument("first")
    parser.add_argument("public")
    args = parser.parse_args()
    result = (check_pair(args.first, args.public) if args.mode == "pair"
              else check_uki(args.first, args.public))
    print(json.dumps(result))


if __name__ == "__main__":
    main()
